apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container-deploy
  namespace: coreconcepts
  labels:
    app: multi-container-app-deployment
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: multi-container-app
  template:
    metadata:
      labels:
        app: multi-container-app
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.25
        ports:
        - containerPort: 80
      - name: busybox-container
        image: busybox
        command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
