apiVersion: v1
kind: Pod
metadata:
  name: sriharsha-multi-container
  labels:
    app: sriharsha-app
spec: 
  containers:
  - name: sh-cont-1
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: sh-cont-2
    image: redis
    ports:
    - containerPort: 6379
